### ISSUE TITLE
Wink API key

### ISSUE THREAD

**Issue by fabaff** [balloob/home-assistant.io#110]
@ki8as reported that the API key generation on the [Wink](https://home-assistant.io/components/wink/) page is no longer working.

**Comment by fabaff** [comment]
https://winkbearertoken.appspot.com/token gives back `Error getting bearer token`.

**Comment by balloob** [comment]
It might be that the Wink API key by @loghound has been revoked.

For now we should update the website while we resolve this.

**Comment by balloob** [comment]
Added a notice to [our wink page](https://home-assistant.io/components/wink/) showing we're having some issues handing out Wink API tokens.

**Comment by ki8as** [comment]
Thanks for the notice.

**Comment by balloob** [comment]
I got in contact with @loghound. He reached out to Wink and said all should be fine. Can anyone test this?

**Comment by Cribstone** [comment]
Wink API generator error- https://home-assistant.io/components/wink/
> Error getting bearer token

**Comment by ki8as** [comment]
I just tried it again and get the same error.

**Comment by loghound** [comment]
Hi Guys -- I just deployed a new build of the server-authentication app -- try again.  if it has an error it should provide more specifics of what went wrong (error code and some text that tells you what the problem was)

Report back here with what you find (it's really working fine in all of my testing so I'm not sure what is going on)

**Comment by ki8as** [comment]
Hi John just tried and it says either my email or password is wrong.  I did
a copy and paste form the email that Wink sent me with the password but
still no go.  I had to send the hub in for up dates not sure if they
changed the pass word or not.  I will have to email them and check it out.

Thanks

Tom C

**Comment by stephenmg12** [comment]
I just tried it. I got the expected configuration information back.

**Comment by loghound** [comment]
I think this is working -- with the new error messages it should be more explanatory when things go bad.

I think we should close this as being a specific issue

**Comment by balloob** [comment]
Closing it for now. Will revisit if issues come back. Thanks @loghound !
